version: 2
updates:
- package-ecosystem: docker-compose
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: composer
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
