version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./users.json:/app/users.json
      - ./app.env:/app/.env
    depends_on:
      - mysql
    env_file:
      - ./app.env

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=csharp_novice
    ports:
      - "3306:3306"
